### ISSUE TITLE
Java bindings on Windows

### ISSUE THREAD

**Issue by drmilhous** [capstone-engine/capstone#299]
I have an executable jar that uses the JNI on OS X and I was trying to get it to run on Windows 8.  I have Java 8 on both, installed the bindings in Windows by copying the dll and lib files to the C:\Windows\System32 directory.  WHen I run the code, It get null values, which I think means that it is not doing the JNI calls correct.  Is there something that I am missing?  Thanks.

**Comment by aquynh** [comment]
The Java binding requires Java JNA to be installed. Perhaps your machine is missing this?

**Comment by drmilhous** [comment]
I downloaded the JNA libraries and put them in the jdk/lib folder.  Are there other detailed instructions that I can use to make sure that I did the process correct.

**Comment by danghvu** [comment]
Can you specify JNA in your classpath `java -classpath [path]/jna.jar:. urtestclass` to make sure it is loaded ?

**Comment by drmilhous** [comment]
So, I ran java -verbose and I get the same libraries as when I run on OS X.
C:/Users/XX/test.jar
C:/Users/XX/test_lib/jna.jar
C:\\Program Files\Java\jre1.8.0_40\lib\jsse.jar
C:\\Program Files\Java\jre1.8.0_40\lib\rt.jar

I copied capstone.dll and capstone.lib to C:\Windows\System32\.  Is this the correct location for those libraries?

**Comment by drmilhous** [comment]
After more research, it appears to be that the only thing that is not moving through is the instruction mnemonic and the opStr.  I get the rest of the data from the binding.  I build from source and the same thing happens.  I am using the 64 bit version on Windows 8. It appears that the libraries are linked properly, as the data is actually being parsed. 

****************
Platform: X86 32 (Intel syntax)
Code: 0x8d 0x4c 0x32 0x08 0x01 0xd8 0x81 0xc6 0x34 0x12 0x00 0x00 0x05 0x23 0x01 0x00 0x00 0x36 0x8b 0x84 0x91 0x23 0x01 0x00 0x00 0x41 0x8d 0x84 0x39 0x89 0x67 0x00 0x00 0x8d 0x87 0x89 0x67 0x00 0x00 0xb4 0xc6
Disasm:
0x1000:	null	null
	Prefix: 0x00 0x00 0x00 0x00 
	Opcode: 0x8d 0x00 0x00 0x00 
	rex: 0x0
	addr_size: 4
	modrm: 0x4c
	disp: 0x8
	sib: 0x32
		sib_base: edx
		sib_index: esi
		sib_scale: 1
	op_count: 2
		operands[0].type: REG = ecx
		operands[0].size: 4
		operands[1].type: MEM
			operands[1].mem.base: REG = edx
			operands[1].mem.index: REG = esi
			operands[1].mem.disp: 0x8
		operands[1].size: 4

**Comment by aquynh** [comment]
make sure that your library (capstone.dll) is not built in `DIET` mode, where mnemonic & opStr are removed to reduce the library size.

few questions:

- which version are you using now? 3.0.2?

- for 3.0.2, can you just use the known-good library download from http://capstone-engine.org/download/3.0.2/capstone-3.0.2-win32.zip (or http://capstone-engine.org/download/3.0.2/capstone-3.0.2-win64.zip for Win64)? try again with this new library to see the problem is solved?

thanks.

**Comment by aquynh** [comment]
i suppose you can just put `capstone.dll` into the same directory with `capstone.jar`. the static lib `capstone.lib` is not needed for Java binding.

**Comment by drmilhous** [comment]
I downloaded the 64 bit library, put it in the same directiory as my java application and I still get the same result.  If I delete the dll the program will not run, so I am sure that it is loading the capstone.dll from that dir.  Is it possible that the 3.0.2 build is build with the DIET turned on?

**Comment by drmilhous** [comment]
ok, it appears that the binding in Java set diet to true, even though the dll supports 

below is the original code.
this.diet = cs.cs_support(CS_SUPPORT_DIET);
I modified it and now it appears to work.
this.diet = false;// cs.cs_support(CS_SUPPORT_DIET);

**Comment by aquynh** [comment]
oh no, your "fix" is not good for many reasons. one of them is `this.diet` is supposed to be private & *read-only*, but not to be modified like what you are doing.

in `capstone-3.0.2-win64.zip`, together with `capstone.dll`, there is `test.exe`. can you paste the output of this `test.exe` here?

also, did you make sure to also get your `capstone.jar` from http://capstone-engine.org/download/3.0.2/capstone.jar ?

**Comment by drmilhous** [comment]
I have downloaded the capstone-3.0.4-win64.zip binary and the issue still exists.  I updated my capstone.jar to the 3.0.4 version also.

**Comment by aquynh** [comment]
can you paste the output of `test.exe` on your machine here?

**Comment by drmilhous** [comment]
C:\Users\Milhous\Downloads\capstone-3.0.4-win64\capstone-3.0.4-win64>test.exe
****************
Platform: X86 16bit (Intel syntax)
Code: 0x8d 0x4c 0x32 0x08 0x01 0xd8 0x81 0xc6 0x34 0x12 0x00 0x00
Disasm:
0x1000: lea             cx, word ptr [si + 0x32]
0x1003: or              byte ptr [bx + di], al
0x1005: fadd            dword ptr [bx + di + 0x34c6]
0x1009: adc             al, byte ptr [bx + si]
0x100b:

****************
Platform: X86 32bit (ATT syntax)
Code: 0x8d 0x4c 0x32 0x08 0x01 0xd8 0x81 0xc6 0x34 0x12 0x00 0x00
Disasm:
0x1000: leal            8(%edx, %esi), %ecx
0x1004: addl            %ebx, %eax
0x1006: addl            $0x1234, %esi
0x100c:

****************
Platform: X86 32 (Intel syntax)
Code: 0x8d 0x4c 0x32 0x08 0x01 0xd8 0x81 0xc6 0x34 0x12 0x00 0x00
Disasm:
0x1000: lea             ecx, dword ptr [edx + esi + 8]
0x1004: add             eax, ebx
0x1006: add             esi, 0x1234
0x100c:

****************
Platform: X86 64 (Intel syntax)
Code: 0x55 0x48 0x8b 0x05 0xb8 0x13 0x00 0x00
Disasm:
0x1000: push            rbp
0x1001: mov             rax, qword ptr [rip + 0x13b8]
0x1008:

****************
Platform: ARM
Code: 0xed 0xff 0xff 0xeb 0x04 0xe0 0x2d 0xe5 0x00 0x00 0x00 0x00 0xe0 0x83 0x22
 0xe5 0xf1 0x02 0x03 0x0e 0x00 0x00 0xa0 0xe3 0x02 0x30 0xc1 0xe7 0x00 0x00 0x53
 0xe3
Disasm:
0x1000: bl              #0xfbc
0x1004: str             lr, [sp, #-4]!
0x1008: andeq           r0, r0, r0
0x100c: str             r8, [r2, #-0x3e0]!
0x1010: mcreq           p2, #0, r0, c3, c1, #7
0x1014: mov             r0, #0
0x1018: strb            r3, [r1, r2]
0x101c: cmp             r3, #0
0x1020:

****************
Platform: THUMB-2
Code: 0x4f 0xf0 0x00 0x01 0xbd 0xe8 0x00 0x88 0xd1 0xe8 0x00 0xf0
Disasm:
0x1000: mov.w           r1, #0
0x1004: pop.w           {fp, pc}
0x1008: tbb             [r1, r0]
0x100c:

****************
Platform: ARM: Cortex-A15 + NEON
Code: 0x10 0xf1 0x10 0xe7 0x11 0xf2 0x31 0xe7 0xdc 0xa1 0x2e 0xf3 0xe8 0x4e 0x62
 0xf3
Disasm:
0x1000: sdiv            r0, r0, r1
0x1004: udiv            r1, r1, r2
0x1008: vbit            q5, q15, q6
0x100c: vcgt.f32                q10, q9, q12
0x1010:

****************
Platform: THUMB
Code: 0x70 0x47 0xeb 0x46 0x83 0xb0 0xc9 0x68
Disasm:
0x1000: bx              lr
0x1002: mov             fp, sp
0x1004: sub             sp, #0xc
0x1006: ldr             r1, [r1, #0xc]
0x1008:

****************
Platform: Thumb-MClass
Code: 0xef 0xf3 0x02 0x80
Disasm:
0x1000: mrs             r0, eapsr
0x1004:

****************
Platform: Arm-V8
Code: 0xe0 0x3b 0xb2 0xee 0x42 0x00 0x01 0xe1 0x51 0xf0 0x7f 0xf5
Disasm:
0x1000: vcvtt.f64.f16           d3, s1
0x1004: crc32b          r0, r1, r2
0x1008: dmb             oshld
0x100c:

****************
Platform: MIPS-32 (Big-endian)
Code: 0x0c 0x10 0x00 0x97 0x00 0x00 0x00 0x00 0x24 0x02 0x00 0x0c 0x8f 0xa2 0x00
 0x00 0x34 0x21 0x34 0x56
Disasm:
0x1000: jal             0x40025c
0x1004: nop
0x1008: addiu           $v0, $zero, 0xc
0x100c: lw              $v0, ($sp)
0x1010: ori             $at, $at, 0x3456
0x1014:

****************
Platform: MIPS-64-EL (Little-endian)
Code: 0x56 0x34 0x21 0x34 0xc2 0x17 0x01 0x00
Disasm:
0x1000: ori             $at, $at, 0x3456
0x1004: srl             $v0, $at, 0x1f
0x1008:

****************
Platform: MIPS-32R6 | Micro (Big-endian)
Code: 0x00 0x07 0x00 0x07 0x00 0x11 0x93 0x7c 0x01 0x8c 0x8b 0x7c 0x00 0xc7 0x48
 0xd0
Disasm:
0x1000: break           7, 0
0x1004: wait            0x11
0x1008: syscall         0x18c
0x100c: rotrv           $t1, $a2, $a3
0x1010:

****************
Platform: MIPS-32R6 (Big-endian)
Code: 0xec 0x80 0x00 0x19 0x7c 0x43 0x22 0xa0
Disasm:
0x1000: addiupc         $a0, 0x64
0x1004: align           $a0, $v0, $v1, 2
0x1008:

****************
Platform: ARM-64
Code: 0x21 0x7c 0x02 0x9b 0x21 0x7c 0x00 0x53 0x00 0x40 0x21 0x4b 0xe1 0x0b 0x40
 0xb9
Disasm:
0x1000: mul             x1, x1, x2
0x1004: lsr             w1, w1, #0
0x1008: sub             w0, w0, w1, uxtw
0x100c: ldr             w1, [sp, #8]
0x1010:

****************
Platform: PPC-64
Code: 0x80 0x20 0x00 0x00 0x80 0x3f 0x00 0x00 0x10 0x43 0x23 0x0e 0xd0 0x44 0x00
 0x80 0x4c 0x43 0x22 0x02 0x2d 0x03 0x00 0x80 0x7c 0x43 0x20 0x14 0x7c 0x43 0x20
 0x93 0x4f 0x20 0x00 0x21 0x4c 0xc8 0x00 0x21
Disasm:
0x1000: lwz             r1, (0)
0x1004: lwz             r1, (r31)
0x1008: vpkpx           v2, v3, v4
0x100c: stfs            f2, 0x80(r4)
0x1010: crand           2, 3, 4
0x1014: cmpwi           cr2, r3, 0x80
0x1018: addc            r2, r3, r4
0x101c: mulhd.          r2, r3, r4
0x1020: bdnzlrl+
0x1024: bgelrl-         cr2
0x1028:

****************
Platform: PPC-64, print register with number only
Code: 0x80 0x20 0x00 0x00 0x80 0x3f 0x00 0x00 0x10 0x43 0x23 0x0e 0xd0 0x44 0x00
 0x80 0x4c 0x43 0x22 0x02 0x2d 0x03 0x00 0x80 0x7c 0x43 0x20 0x14 0x7c 0x43 0x20
 0x93 0x4f 0x20 0x00 0x21 0x4c 0xc8 0x00 0x21
Disasm:
0x1000: lwz             1, (0)
0x1004: lwz             1, (31)
0x1008: vpkpx           2, 3, 4
0x100c: stfs            2, 0x80(4)
0x1010: crand           2, 3, 4
0x1014: cmpwi           2, 3, 0x80
0x1018: addc            2, 3, 4
0x101c: mulhd.          2, 3, 4
0x1020: bdnzlrl+
0x1024: bgelrl-         cr2
0x1028:

****************
Platform: Sparc
Code: 0x80 0xa0 0x40 0x02 0x85 0xc2 0x60 0x08 0x85 0xe8 0x20 0x01 0x81 0xe8 0x00
 0x00 0x90 0x10 0x20 0x01 0xd5 0xf6 0x10 0x16 0x21 0x00 0x00 0x0a 0x86 0x00 0x40
 0x02 0x01 0x00 0x00 0x00 0x12 0xbf 0xff 0xff 0x10 0xbf 0xff 0xff 0xa0 0x02 0x00
 0x09 0x0d 0xbf 0xff 0xff 0xd4 0x20 0x60 0x00 0xd4 0x4e 0x00 0x16 0x2a 0xc2 0x80
 0x03
Disasm:
0x1000: cmp             %g1, %g2
0x1004: jmpl            %o1+8, %g2
0x1008: restore         %g0, 1, %g2
0x100c: restore
0x1010: mov             1, %o0
0x1014: casx            [%i0], %l6, %o2
0x1018: sethi           0xa, %l0
0x101c: add             %g1, %g2, %g3
0x1020: nop
0x1024: bne             0x1020
0x1028: ba              0x1024
0x102c: add             %o0, %o1, %l0
0x1030: fbg             0x102c
0x1034: st              %o2, [%g1]
0x1038: ldsb            [%i0+%l6], %o2
0x103c: brnz,a,pn               %o2, 0x1048
0x1040:

****************
Platform: SparcV9
Code: 0x81 0xa8 0x0a 0x24 0x89 0xa0 0x10 0x20 0x89 0xa0 0x1a 0x60 0x89 0xa0 0x00
 0xe0
Disasm:
0x1000: fcmps           %f0, %f4
0x1004: fstox           %f0, %f4
0x1008: fqtoi           %f0, %f4
0x100c: fnegq           %f0, %f4
0x1010:

****************
Platform: SystemZ
Code: 0xed 0x00 0x00 0x00 0x00 0x1a 0x5a 0x0f 0x1f 0xff 0xc2 0x09 0x80 0x00 0x00
 0x00 0x07 0xf7 0xeb 0x2a 0xff 0xff 0x7f 0x57 0xe3 0x01 0xff 0xff 0x7f 0x57 0xeb
 0x00 0xf0 0x00 0x00 0x24 0xb2 0x4f 0x00 0x78
Disasm:
0x1000: adb             %f0, 0
0x1006: a               %r0, 0xfff(%r15, %r1)
0x100a: afi             %r0, -0x80000000
0x1010: br              %r7
0x1012: xiy             0x7ffff(%r15), 0x2a
0x1018: xy              %r0, 0x7ffff(%r1, %r15)
0x101e: stmg            %r0, %r0, 0(%r15)
0x1024: ear             %r7, %a8
0x1028:

****************
Platform: XCore
Code: 0xfe 0x0f 0xfe 0x17 0x13 0x17 0xc6 0xfe 0xec 0x17 0x97 0xf8 0xec 0x4f 0x1f
 0xfd 0xec 0x37 0x07 0xf2 0x45 0x5b 0xf9 0xfa 0x02 0x06 0x1b 0x10
Disasm:
0x1000: get             r11, ed
0x1002: ldw             et, sp[4]
0x1004: setd            res[r3], r4
0x1006: init            t[r2]:lr, r1
0x100a: divu            r9, r1, r3
0x100e: lda16           r9, r3[-r11]
0x1012: ldw             dp, dp[0x81c5]
0x1016: lmul            r11, r0, r2, r5, r8, r10
0x101a: add             r1, r2, r3
0x101c:


C:\Users\Milhous\Downloads\capstone-3.0.4-win64\capstone-3.0.4-win64>
